weixin:
    signal: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    detail: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    error: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
email:
    host: 'smtp.qq.com'
    uid: 'xxxxxx@qq.com'
    pwd: 'xxxxxxxxxxxxx'
    email: 'xxxxxx@qq.com,xxxxx@qq.com'
plusplus:
    token: 'xxxxxxxxxxxxxx'
qyweixin:
    agent_id: 'xxxxxxx'
    secret: 'xxxxxxxxxxxxxxxxxx'
    corp_id: 'xxxxxxxxxxxxxxxxxx'